### ISSUE TITLE
`add-backup-drive` icons are not scaled correctly

### ISSUE THREAD

**Issue by cassidyjames** [chasinglogic/tardis#21]
Even though your icons are SVGs, just providing the same icon named or resized to a smaller size doesn't scale properly; it ends up looking fuzzy and especially 1px strokes end up getting lost. Instead, the icon should be redrawn at each target size.

Since this icon specifically looks to be composed from existing elementary icons, it shouldn't be _too_ hard to compose correct versions at each size—especially 24px since that's what's immediately visible (and blurry) in the header bar.

**Comment by chasinglogic** [comment]
I've changed how backup drives are added and removed this icon
