### ISSUE TITLE
Same disk twice in dropdown of welcome screen

### ISSUE THREAD

**Issue by ezeveliz** [chasinglogic/tardis#28]
I couldn't take a screenshot with the dropdown open, but here is the photo

![IMG_20200221_174740](https://user-images.githubusercontent.com/24837065/75070830-d4e71200-54d2-11ea-88e4-0722610aa6fc.jpg)

**Comment by chasinglogic** [comment]
Does the drive show up twice in Files? (In the sidebar to be mounted)

**Comment by ezeveliz** [comment]
In Files it shows up twice because they're different partitions of the same drive

**Comment by chasinglogic** [comment]
Which is why they show up twice here, Tardis uses the same underlying API (Glib.VolumeMonitor) to query for the available drives.

Does Files somehow differentiate them in it's display? If so I can use the same code to make the distinction when listing them.

**Comment by ezeveliz** [comment]
Yes, each one has its own name

**Comment by chasinglogic** [comment]
I will investigate then, thanks for the bug report!
