### ISSUE TITLE
Change requested for AppCenter: Add release description

### ISSUE THREAD

**Issue by cassidyjames** [chasinglogic/tardis#33]
Thanks for submitting an update to AppCenter! The update itself looks good, but while reviewing we noticed there is no release description in your AppData. You must include release descriptions to aid the review process and to inform users what an update does. You can [read more here](https://github.com/elementary/houston/wiki/Publishing-Updates#release-descriptions), but here's the important bit:

>You must add accurate release descriptions to your appdata.xml file when publishing an update. For more information on formatting, see the [FreeDesktop.org AppStream documentation](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#sect-Metadata-GenericComponent) for the <releases/> tag. The version in your release should match the latest version submitted to AppCenter.
>
>Release descriptions should be accurate, concise, and written for a typical user of your app—focus on user-visible and user-understandable changes, and simplify or omit technical "under the hood" changes. 

Please update your AppData and submit a new release (i.e. 1.2.1) with a matching release description. In this case, you can provide a single 1.2.1 description for the cumulative changes since 1.2.0 was not released to users.

As always, let me know if you have any questions!

**Comment by chasinglogic** [comment]
I've added the requested tags to the appdata, cut the 1.2.1 release and submitted it to AppCenter.
