### ISSUE TITLE
Change required for AppCenter: each release needs a description

### ISSUE THREAD

**Issue by cassidyjames** [chasinglogic/tardis#43]
Thanks for submitting your 1.2.2 update to AppCenter! However, while reviewing the submission, we found an issue that needs to be resolved.

Updates must include accurate [release descriptions](https://docs.elementary.io/develop/appcenter/publishing-updates#release-descriptions). Please detail the user-facing changes in the proper tag.

Once you've made the requested changes, create a new release on GitHub and re-submit it to the [AppCenter Dashboard](https://developer.elementary.io). You can include the 1.2.2 details in the next version's release description since 1.2.2 will have never reached users (and release nubmers are immutable).

As always, if you have any questions you can reply here.

**Comment by chasinglogic** [comment]
@cassidyjames Is it possible to remove an app from AppCenter?

I have not actively maintained this project for quite some time and have not been an elementary OS user for even longer. I'm trying to remove the price with this update as I also shut down my Stripe account.

I'd like people to stop installing the app to prevent support issues coming to my inbox.

**Comment by cassidyjames** [comment]
I'm sorry to hear that.

We don't currently support unpublishing apps from an existing OS release as an app disappearing out from under users e.g. when they go to install it on another machine would be a bad experience—and since all AppCenter apps are open source, anyone could download and compile the source code themselves anyway.

The recommended way to handle that on AppCenter would be to push an update with information in the AppData about the support situation, as well as an in-app message if you choose. Once elementary OS 6 is released, simply don't update your app for the new release and it will not be made available on AppCenter for elementary OS 6 and later.

**Comment by chasinglogic** [comment]
Understood, I will simply then just wait for OS 6 to come out and archive this repository to avoid confusion.
